#!/bin/bash

echo ""
echo "starting bootstrap"
echo ""

## install brew
if ! command -v brew >/dev/null 2>&1; then
    echo "brew: installing"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "brew: skipped - brew is already installed"
fi

## install brewfile
if [[ -f ~/.dotfiles/Brewfile ]];then
    if ! brew bundle check --file="${HOME}/.dotfiles/Brewfile" > /dev/null; then
      echo "brewfile: installing - adjusting desired dependencies"
      brew bundle install --file="${HOME}/.dotfiles/Brewfile"
    else
      echo "brewfile: skipping - everythings seems to be fine"
    fi
else
  echo "brewfile: skipping - no brewfile found"
fi

## install latest node lts as default via nvm
echo "nvm: installing latest lts node version"
nvm install --lts
echo "nvm: setting latest lts node as global default"
nvm alias default node
echo "nvm: switching to latest lts"
nvm use default
echo "nvm: installing latest npm version"
nvm install-latest-npm

# # set zsh as default shell
# chsh -s /usr/local/bin/zsh

# ## install zplug
# if [[ ! -d ~/.zplug ]];then
#   echo "installing zplug"
#   curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
# else
#   echo "zplug already installed"
# fi

# ## install zplug plugins
