tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "bash"
brew "cloc"
brew "ctop"
brew "git"
brew "jq"
brew "mas"
brew "nvm"
brew "rclone"
brew "speedtest-cli"
brew "tree"
brew "wallpaper"
brew "zsh"

# cask "appcleaner"
# cask "hyper"
# cask "insomnia"
# cask "transmit"
# cask "vlc"

# mas "Amphetamine", id: 937984704
# mas "Disk Graph", id: 697942581
# mas "iStat Mini", id: 927292435
# mas "Keynote", id: 409183694
# mas "Numbers", id: 409203825
# mas "Pages", id: 409201541
# mas "Spark", id: 1176895641
# mas "The Unarchiver", id: 425424353
# mas "Things", id: 904280696
# mas "Trello", id: 1278508951