#!/bin/bash

## install brew
if ! command -v brew >/dev/null 2>&1; then
    echo "installing brew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "brew already installed"
fi

## install brewfile
echo "looking for global Brewfile"
if [[ -f ~/.Brewfile ]];then
    echo "global Brewfile found"
    echo "looking for missing dependencies"

    if ! brew bundle check --no-upgrade --global > /dev/null; then
      echo "installing brew packages"
      brew bundle exec -- bundle install --global --verbose
    else
      echo "everythings seems to be fine"
    fi
else
  echo "skipping: no global Brewfile found"
fi

## install nvm
echo "looking for nvm"
if [[ ! -f ~/.nvm/nvm.sh ]]; then
  echo "nvm doesn't exist -> installing nvm"
  curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
else
  echo "nvm already installed -> skipping"
fi
echo "loading nvm"
\. "$HOME/.nvm/nvm.sh"


## set default nvm version
echo "install latest node version"
nvm install node --latest-npm 1>/dev/null
echo "setting latest node as default"
nvm alias default node 1>/dev/null
echo "switching to latest version"
nvm use default 1>/dev/null

# ## install global dependencies


# set zsh as default shell
chsh -s /usr/local/bin/zsh

## install zplug
if [[ ! -d ~/.zplug ]];then
  echo "installing zplug"
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
else
  echo "zplug already installed"
fi

## install zplug plugins 


